inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - default.yml

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.1
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Enabled: 111 # TODO: discuss and set this

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false
